### ISSUE TITLE
Support for incremental updates to the index

### ISSUE THREAD

**Issue by prvnsmpth** [sourcegraph/lsif-py#15]
Re-building the entire index from scratch on every code change to a project is hardly ideal, especially for large projects. Is it feasible to implement support for incremental updates to the index? The incremental indexer could take as input a previously generated language graph and the diff of changes to the codebase, and use that to output the delta that should be applied to the old graph to get the new one.

**Comment by macraig** [comment]
`lsif-py` is now considered deprecated, please use https://github.com/sourcegraph/scip-python instead.
